export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  COMPANY_ADMIN: 'COMPANY_ADMIN',
  AGENT: 'AGENT',
  BROKER: 'BROKER',
  PROPERTY_MANAGER: 'PROPERTY_MANAGER',
  VIEWER: 'VIEWER',
} as const;

export const PERMISSIONS = {
  // Property Management
  VIEW_PROPERTIES: 'VIEW_PROPERTIES',
  CREATE_PROPERTY: 'CREATE_PROPERTY',
  EDIT_PROPERTY: 'EDIT_PROPERTY',
  DELETE_PROPERTY: 'DELETE_PROPERTY',
  APPROVE_PROPERTY: 'APPROVE_PROPERTY',

  // Lead Management
  VIEW_LEADS: 'VIEW_LEADS',
  CREATE_LEAD: 'CREATE_LEAD',
  EDIT_LEAD: 'EDIT_LEAD',
  ASSIGN_LEAD: 'ASSIGN_LEAD',
  DELETE_LEAD: 'DELETE_LEAD',

  // Document Management
  VIEW_DOCUMENTS: 'VIEW_DOCUMENTS',
  CREATE_DOCUMENT: 'CREATE_DOCUMENT',
  EDIT_DOCUMENT: 'EDIT_DOCUMENT',
  DELETE_DOCUMENT: 'DELETE_DOCUMENT',
  APPROVE_DOCUMENT: 'APPROVE_DOCUMENT',

  // Team Management
  VIEW_TEAM: 'VIEW_TEAM',
  MANAGE_TEAM: 'MANAGE_TEAM',
  ASSIGN_ROLES: 'ASSIGN_ROLES',

  // Company Management
  VIEW_COMPANY: 'VIEW_COMPANY',
  MANAGE_COMPANY: 'MANAGE_COMPANY',
  
  // Analytics & Reports
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  GENERATE_REPORTS: 'GENERATE_REPORTS',
  
  // Settings
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
} as const;

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN: [
    PERMISSIONS.VIEW_PROPERTIES,
    PERMISSIONS.CREATE_PROPERTY,
    PERMISSIONS.EDIT_PROPERTY,
    PERMISSIONS.DELETE_PROPERTY,
    PERMISSIONS.APPROVE_PROPERTY,
    PERMISSIONS.VIEW_LEADS,
    PERMISSIONS.CREATE_LEAD,
    PERMISSIONS.EDIT_LEAD,
    PERMISSIONS.ASSIGN_LEAD,
    PERMISSIONS.DELETE_LEAD,
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.CREATE_DOCUMENT,
    PERMISSIONS.EDIT_DOCUMENT,
    PERMISSIONS.DELETE_DOCUMENT,
    PERMISSIONS.APPROVE_DOCUMENT,
    PERMISSIONS.VIEW_TEAM,
    PERMISSIONS.MANAGE_TEAM,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.GENERATE_REPORTS,
    PERMISSIONS.MANAGE_SETTINGS,
  ],
  COMPANY_ADMIN: [
    PERMISSIONS.VIEW_PROPERTIES,
    PERMISSIONS.CREATE_PROPERTY,
    PERMISSIONS.EDIT_PROPERTY,
    PERMISSIONS.VIEW_LEADS,
    PERMISSIONS.CREATE_LEAD,
    PERMISSIONS.EDIT_LEAD,
    PERMISSIONS.ASSIGN_LEAD,
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.CREATE_DOCUMENT,
    PERMISSIONS.EDIT_DOCUMENT,
    PERMISSIONS.VIEW_TEAM,
    PERMISSIONS.MANAGE_TEAM,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.GENERATE_REPORTS,
    PERMISSIONS.MANAGE_SETTINGS,
  ],
  AGENT: [
    PERMISSIONS.VIEW_PROPERTIES,
    PERMISSIONS.CREATE_PROPERTY,
    PERMISSIONS.EDIT_PROPERTY,
    PERMISSIONS.VIEW_LEADS,
    PERMISSIONS.CREATE_LEAD,
    PERMISSIONS.EDIT_LEAD,
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.CREATE_DOCUMENT,
    PERMISSIONS.VIEW_ANALYTICS,
  ],
  BROKER: [
    PERMISSIONS.VIEW_PROPERTIES,
    PERMISSIONS.CREATE_PROPERTY,
    PERMISSIONS.EDIT_PROPERTY,
    PERMISSIONS.VIEW_LEADS,
    PERMISSIONS.CREATE_LEAD,
    PERMISSIONS.EDIT_LEAD,
    PERMISSIONS.ASSIGN_LEAD,
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.CREATE_DOCUMENT,
    PERMISSIONS.VIEW_ANALYTICS,
  ],
  PROPERTY_MANAGER: [
    PERMISSIONS.VIEW_PROPERTIES,
    PERMISSIONS.EDIT_PROPERTY,
    PERMISSIONS.VIEW_LEADS,
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.CREATE_DOCUMENT,
    PERMISSIONS.VIEW_ANALYTICS,
  ],
  VIEWER: [
    PERMISSIONS.VIEW_PROPERTIES,
    PERMISSIONS.VIEW_LEADS,
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.VIEW_ANALYTICS,
  ],
};
