export enum DocumentStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
  DELETED = 'DELETED'
}

export enum DocumentSecurity {
  INTERNAL = 'INTERNAL',
  EXTERNAL = 'EXTERNAL',
  PUBLIC = 'PUBLIC'
}

export enum DocumentFormat {
  PDF = 'PDF',
  WORD = 'WORD',
  EXCEL = 'EXCEL',
  PPT = 'PPT',
  PNG = 'PNG',
  JPEG = 'JPEG',
  GIF = 'GIF',
  JPG = 'JPG',
  CSV = 'CSV',
  OTHER = 'OTHER'
}

export enum DocumentType {
  CONTRACT = 'CONTRACT',
  PROPOSAL = 'PROPOSAL',
  MEMO = 'MEMO',
  LETTER = 'LETTER',
  MEMORANDUM = 'MEMORANDUM',
  REPORT = 'REPORT',
  FORM = 'FORM',
  OTHER = 'OTHER'
}

export enum FileCategory {
  CONTRACT = 'CONTRACT',
  ADDENDUM = 'ADDENDUM',
  ID_VERIFICATION = 'ID_VERIFICATION',
  TITLE_DEED = 'TITLE_DEED',
  PROPERTY_IMAGE = 'PROPERTY_IMAGE',
  INSPECTION_REPORT = 'INSPECTION_REPORT',
  PAYMENT_RECEIPT = 'PAYMENT_RECEIPT',
  LEGAL_OPINION = 'LEGAL_OPINION',
  GOVERNMENT_FORM = 'GOVERNMENT_FORM',
  OTHER = 'OTHER'
}

export enum Language {
  ENGLISH = 'ENGLISH',
  ARABIC = 'ARABIC',
  FRENCH = 'FRENCH',
  GERMAN = 'GERMAN',
  CHINESE = 'CHINESE',
  HINDI = 'HINDI',
  SPANISH = 'SPANISH',
  RUSSIAN = 'RUSSIAN',
  ITALIAN = 'ITALIAN',
  TURKISH = 'TURKISH',
  PORTUGUESE = 'PORTUGUESE',
  JAPANESE = 'JAPANESE',
  KOREAN = 'KOREAN',
  SWAHILI = 'SWAHILI',
  PERSIAN = 'PERSIAN'
}